name: Build & Test

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

env:
  DOTNET_VERSION: 9.0.x

jobs:
  api:
    name: API Pipeline
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: ./.github/actions/dotnet-setup
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore PantryPal.sln

      - name: Run unit tests
        run: dotnet test tests/PantryPal.Api.UnitTests/PantryPal.Api.UnitTests.csproj --configuration Release --no-restore

  android:
    name: Android Pipeline
    runs-on: windows-latest
    env:
      MAUI_TARGET_FRAMEWORK: net9.0-android
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET SDK with MAUI
        uses: ./.github/actions/dotnet-setup
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          install-maui: 'true'
          maui-platform: 'android'

      - name: Restore dependencies
        run: dotnet restore PantryPal.sln

      - name: Run unit tests
        run: dotnet test tests/PantryPal.Mobile.UnitTests/PantryPal.Mobile.UnitTests.csproj --configuration Release --no-restore
